site_name: C++ Jegyzet - Lipódi László
theme:
  name: material
  palette:
    primary: black
    accent: indigo
    scheme: slate
    features:
      - content.code.copy
    logo: assets/favicon.png
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - pymdownx.blocks.tab
  - pymdownx.emoji
  - md_in_html

plugins:
   - search
   - awesome-nav
   - tags:
      enabled: true
      tags: true
   - macros